base: !include base.yaml

num_epochs: 300
batch_size: 1
lr: 0.0005
device: cuda:0

model: "GNOFNOGNOAhmed" 
subsample_train: 1
subsample_eval: 1
weighted_kernel: False

radius_in: 0.055 
radius_out: 0.055 
embed_dim: 32
hidden_channels: [64,64] 
in_channels: 2
out_channels: 1 # pressure
fno_modes: [32, 32, 32] 
fno_hidden_channels: 64 
fno_out_channels: 64
max_in_points: 5000 # or 3000

run_name: 'GNOFNOGNOAhmed_300 epoch'
project_name: "ahmed-body"

data_path: "ahmed-body-dataset"
data_module: "AhmedBodyDataModule"
sdf_spatial_resolution: [64, 64, 64] # or [70, 70, 70]